version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    profiles:
      - prod

  # Production service with custom port
  app-prod-custom:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    profiles:
      - prod-custom
