name: Frontend Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  Frontend-Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "Cook .env file..."
          echo "${{ vars.FRONTEND_APP_ENV }}" > .env

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: .
          remote_path: ${{ vars.FRONTEND_PATH }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: SSH to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_PUBLIC_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd ${{ vars.DOCKER_COMPOSE_PATH }}
            docker compose up -d --build --force-recreate --no-deps frontend
