version: "3.8"

services:

  backend:
    build:
      context: ./backend
    container_name: [PROJECTNAME_PH]-[ENVIRONMENT_PH]-backend
    restart: unless-stopped
    ports:
      - "8080:8080" #hostport:containerport
    env_file:
      - ./backend/.env
    networks:
      - [PROJECTNAME_PH]-[ENVIRONMENT_PH]-network

  frontend:
    build:
      context: ./frontend
    container_name: [PROJECTNAME_PH]-[ENVIRONMENT_PH]-frontend
    restart: unless-stopped
    ports:
      - "80:80" #hostport:containerport
    env_file:
      - ./frontend/.env
    networks:
      - [PROJECTNAME_PH]-[ENVIRONMENT_PH]-network

networks:
  [PROJECTNAME_PH]-[ENVIRONMENT_PH]-network:
    driver: bridge